### ISSUE TITLE
node.tpl.php creates a DOM element to handle "unpublished", do we need a DOM element for it?

### ISSUE THREAD

**Issue by webthingee** [Lullabot/windup#1]
node.tpl.php

```
<?php if ($unpublished): ?>
    <mark class="unpublished"><?php print t('Unpublished'); ?></mark>
<?php endif; ?>
```

**Comment by carwin** [comment]
I'm good with @justafish's suggestion here. Although, I would prefer the status and view mode classes didn't act like _modifier_ classes. Since these are essentially utility classes we should probably do:

```
status-<status>
view-mode-<view_mode>
```

I don't see a situation where we'd ever have a default `status` or `view-mode` class, so double dashes don't match our component patterns.

**Comment by krisbulman** [comment]
this was worked out in IRC and we were all agreed that these are pretty much utility classes and would never be used in a component context.

**Comment by justafish** [comment]
PR updated https://github.com/Lullabot/windup/pull/27

**Comment by krisbulman** [comment]
PR looks good to me @carwin @justafish

**Comment by carwin** [comment]
Boom, merged. Thanks @justafish.
