### ISSUE TITLE
Best practices for .gitignore

### ISSUE THREAD

**Issue by fender** [Lullabot/windup#38]
For several projects that I am working on, the Github repository is cloned onto the server and an admin SSH's in to `git pull` if there is changes to deploy. The `.gitignore` prevents committing `bower_components` or `css/style.css` which means we would have to re-compile on the server. I've removed those as I want to keep those items tracked in version control.

What's the benefits to having these files ignored?

**Comment by tlattimore** [comment]
IMO, any code that can be built with a build tool should built as part of the continuous integration process. This includes Sass, bower, and anything else that is downloaded via package manager like npm or bundler. Not versioning these items has 2 advantages:

1. **Helps prevent merge conflicts.**
    - This is especially relevant when Sass is in the mix. When a few devs version of a compiled CSS file are in play, complex merge conflicts are inevitable.
1. **Keeps the repo smaller.**
     - The components that bower, npm, and bundler store can get pretty large... No reason to version them when they can be managed in an automated fashion. 

Because we don't always control the continuous integration environment that clients have, this may not always be possible. But I think the `.gitignore` should be left in to encouragement best practice.

**Comment by carwin** [comment]
I'm inclined to agree with @tlattimore here. If we want to revisit this let's re-open it.
