### ISSUE TITLE
[Re: #55] Get WireDep working for D8

### ISSUE THREAD

**Issue by wesruv** [Lullabot/windup#57]
From @tlattimore :
This is actually going to be a quite difficult in contrast to how we have wiredep setup for D7 as now libraries are declared in separate .yml files fromt the .info.

**Comment by carwin** [comment]
I'd like to assign this to @justafish, but for some reason I'm unable to.

**Comment by carwin** [comment]
Figured it out, I had to add her as a collaborator.

**Comment by carwin** [comment]
So essentially for windup there are two pieces to this puzzle. I created a `bower` library in `windup.libraries.yml`, and that contains the comment placeholders that `wiredep` hooks into. Then I include the `bower` library in `windup.info.yml`. 

Our `_vendor.scss` stays the same and I've excluded any jQuery dependency so that'll never get added.

If anyone finds problems open a new issue.
